wandb:
  project: Bart-xsum
  exp_num: 1
  tags: [bart]
path:
  checkpoint_path: checkpoints
model:
  document_max_length: 1024
  summary_max_length: 400
training:
  test_size: 0.3
  n_epochs: 10
  batch_size: 2
  learning_rate: 0.01
  text_column_name: article
  label_column_name: label
callbacks:
  patience: 5
  patience_min_delta: 0