wandb:
  project: Bart-xsum
  exp_num: 1
  tags: [bart]
path:
  checkpoint_path: checkpoints
model:
  d_model: 768
  n_classes: 9
  max_length: 512
training:
  test_size: 0.3
  n_epochs: 10
  batch_size: 32
  learning_rate: 0.01
  text_column_name: article
  label_column_name: label
callbacks:
  patience: 5
  patience_min_delta: 0