wandb:
  project: Bart-xsum
  exp_num: 1
  tags: [bart]
bart_model:
  pretrained_model_name : 'facebook/bart-base'
  epoch : 2
  seed : 40
  accumulate_grad_batches: 1
  data_module: 
    batch_size : 2
    document_max_length: 1024
    summary_max_length: 400
  optimizer:
    name : "RAdam"
    lr : 1e-5
  early_stopping :
    monitor: "val/loss"
    patience: 3
    mode : "min"
    min_delta: 0.02
  checkpoint :
    monitor: "val/loss"
    mode: "min"
    filename: "2" #ここよくわからん
    verbose: True
