method: "random"
metric:
  goal: "minimize"
  name: "val/loss"
parameters:
  data_module:
    parameters:
      batch_size:
        values: [1, 2, 3, 4]
        document_max_length: 1024
        summary_max_length: 400 #データセットの要約の最大が399語だった
  optimizer:
    parameters:
      name:
        values: ["AdamW", "RAdam"]
      lr:
        values: [1e-5, 5e-5, 9e-5, 1e-6]